# Generated by Django 6.0.1 on 2026-02-20 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_findly', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='found_item',
            new_name='found_itemID',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='lost_item',
            new_name='lost_itemID',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='match',
            new_name='matchID',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='senderID',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='authorID',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='item',
            new_name='itemID',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='target_user',
            new_name='target_userID',
        ),
        migrations.RemoveField(
            model_name='item',
            name='reporter',
        ),
        migrations.AddField(
            model_name='item',
            name='reporterID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
