# Generated by Django 6.0.1 on 2026-02-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.IntegerField(null=True),
        ),
    ]
