# Generated by Django 6.0.1 on 2026-02-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_studentemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productprice', models.ImageField(upload_to='')),
                ('productDescription', models.TextField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
