# Generated by Django 6.0.1 on 2026-02-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_product_productcolor_product_productstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'studentAttendance',
            },
        ),
    ]
