# Generated by Django 6.0.1 on 2026-02-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_category_service_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentAge',
            field=models.IntegerField(),
        ),
    ]
