# Generated by Django 6.0.1 on 2026-02-06 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_studentacademicinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLibraryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_card_no', models.CharField(max_length=20)),
                ('issued_books', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
